---

  - name: destroy VM
    command: virsh destroy {{ vm }}

  - name: undefine VM
    command: virsh undefine {{ vm }}

  - name: delete VM files
    file: "path={{ kvm_vm_dir }}/{{ vm }} state=absent"
    ignore_errors: true
    become: true

  - name: delete lv
    command: "lvremove /dev/{{ kvm_vol_group }}/{{ vm.name }}_lv"
    become: true


