---

  - name: create vm dir
    file: "path={{ kvm_vm_dir }}/{{ vm.name }} state=directory"

  - name: copy vm template
    command: "cp {{ kvm_template.image }} {{ kvm_vm_dir }}/{{ vm.name }}/{{ vm.name }}.qcow2 creates={{ kvm_vm_dir }}/{{ vm.name }}/{{ vm.name }}.qcow2"
    register: image_file

  - name: resize image
    command: "qemu-img resize {{ kvm_vm_dir }}/{{ vm.name }}/{{ vm.name }}.qcow2 +{{ vm.disk }}GB"
    when: image_file.changed

  - name: create meta-data file
    template: "src=meta-data.j2 dest={{ kvm_vm_dir }}/{{ vm.name }}/meta-data"
    register: user_data

  - name: create meta-data file
    template: "src=user-data.j2 dest={{ kvm_vm_dir }}/{{ vm.name }}/user-data"
    register: meta_data

  - name: create config.iso
    command: "genisoimage -o {{ kvm_vm_dir }}/{{ vm.name }}/config.iso -V cidata -r -J {{ kvm_vm_dir }}/{{ vm.name }}/meta-data {{ kvm_vm_dir }}/{{ vm.name }}/user-data"
    when: meta_data.changed or user_data.changed

  - name: create VM
    command: >
        virt-install \
            --name {{ vm.name }} \
            --vcpus {{ vm.cpu }} \
            --ram {{ vm.ram }} \
            --hvm \
            --cpu host \
            --os-type=linux \
            --os-variant=ubuntu16.04 \
            --network bridge:virbr10,mac={{ vm.mac }} \
            --disk path={{ kvm_vm_dir }}/{{ vm.name }}/config.iso,device=cdrom \
            --disk path={{ kvm_vm_dir }}/{{ vm.name }}/{{ vm.name }}.qcow2,format=qcow2 \
            --import \
            --autostart \
            --nographics \
            --noautoconsole
