---

  - name: destroy VM
    command: virsh destroy {{ vm }}
    tags: vms

  - name: undefine VM
    command: virsh undefine {{ vm }}
    tags: vms

  - name: delete VM files
    file: "path={{ kvm_vm_dir }}/{{ vm }} state=absent"
    ignore_errors: true
    become: true
    tags: vms


