---

  - name: remove libvirt file
    file: path=/etc/dnsmasq.d/libvirt-bin state=absent
    become: true

  - name: add conf file
    template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.d/dnsmasq.conf
    become: true
    notify: dnsmasq_reload

  - name: create hosts file
    command: "touch /var/lib/libvirt/dnsmasq/{{ bridge.name }}.hostsfile"
    args:
      creates: "/var/lib/libvirt/dnsmasq/{{ bridge.name }}.hostsfile"
    become: true

  - name: install dnsmasq
    apt: pkg=dnsmasq
    become: true


