---

  - name: remove libvirt file
    file: path=/etc/dnsmasq.d/libvirt-bin state=absent
    become: true

  - name: add conf file
    template: src=dnsmasq/conf.j2 dest=/etc/dnsmasq.conf
    become: true
    notify: dnsmasq_reload

  - name: add hosts file
    template: src=dnsmasq/hosts.j2 dest=/etc/dnsmasq.hosts
    become: true
    notify: dnsmasq_reload

  - name: add dnsmasq resolv file
    template: src=dnsmasq/resolv.conf.j2 dest=/etc/resolv.conf
    become: true
    notify: dnsmasq_reload

  - name: create hosts file
    command: "touch /var/lib/libvirt/dnsmasq/{{ kvm_net.bridge.name }}.hostsfile"
    args:
      creates: "/var/lib/libvirt/dnsmasq/{{ kvm_net.bridge.name }}.hostsfile"
    become: true

  - name: install dnsmasq
    apt: pkg=dnsmasq
    become: true


