---

  - name: Install packages
    apt: name={{ item }} state=installed update_cache=yes install_recommends=no
    with_items:
      - qemu-kvm
      - libvirt-bin
      - libvirt-dev
      - bridge-utils
      - qemu-utils
      - virtinst
      - libosinfo-bin
      - genisoimage
    become: true

