---

  - name: Install base apps
    include: install.yml

  - name: setup network
    include: network.yml

  - name: configure iptables
    include: iptables.yml

  - name: setup dnsmasq
    include: dnsmasq.yml

  - name: download ubuntu image
    include: data.yml

  - name: manage vms
    include: managevms.yml
