---

  - name: reserve IP address
    template: src=dnsmasq.resv.j2 dest=/var/lib/libvirt/dnsmasq/{{ kvm_net.bridge.name }}.hostsfile
    become: true
    notify: dnsmasq_reload

  - meta: flush_handlers

  - name: delete VMs
    include: del_vm.yml
    loop_control:
        loop_var: vm
    with_items: "{{ kvm_delete_vms }}"
    when: kvm_delete_vms|length > 0


  - name: manage VMs
    include: vm.yml
    loop_control:
        loop_var: vm
    with_items: "{{ kvm_vms }}"
    when: kvm_vms|length > 0




